package com.example.springboot.mapper;

import com.example.springboot.model.TUser;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

//@Mapper
public interface TUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Thu Mar 21 19:48:27 CST 2019
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Thu Mar 21 19:48:27 CST 2019
     */
    int insert(TUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Thu Mar 21 19:48:27 CST 2019
     */
    int insertSelective(TUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Thu Mar 21 19:48:27 CST 2019
     */
    TUser selectByPrimaryKey(Integer userId);

    List<TUser> selectAllUser();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Thu Mar 21 19:48:27 CST 2019
     */
    int updateByPrimaryKeySelective(TUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Thu Mar 21 19:48:27 CST 2019
     */
    int updateByPrimaryKey(TUser record);
}